sass:
  sass_dir: _sass
  style: compressed

exclude: [".idea/"]


title: Perfection Painting
email: sierra.v.moore@gmail.com
description: painting company, house painting, commercial painting, wood finishing, wall repair, paint touch up, santa barbara, california painters, best painting companies,
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.perfectionpainting.com
github_username:  sierramoore
repository: https://github.com/sierramoore/perfection_painting

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed




#plugins:
#  - jekyll-sitemap
#  - jekyll-autoprefixer
#
#autoprefixer:
#  browsers:
#    - last 10 versions



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
